server:
  port: 9191
  servlet:
    context-path: /as
    session:
      timeout: 60 # Session timeout in seconds, to require periodic client re-authentication

security:
  oauth2:
    authorization:
      jwt:
        key-store: classpath:authorization-server.jks # For asymmetric signing of access token
        key-store-password: Super Secret JWT Keypass
        key-alias: authorization-server

bouvet:
  authorization:
    users:
      - username: oauth2-user
        password: user-password
        authorities:
          - USER
          - USER_PLUS
      - username: oauth2-admin
        password: admin-password
        authorities:
          - USER
          - ADMIN
    clients:
      - client-id: oauth2-client
        secret: client-password
        grant-types:
          - authorization_code
        scopes:
          - read
        allowed-authorities:
          - USER
        redirect-uris:
          - http://localhost:9291/login

logging:
  level:
    org.springframework: DEBUG
    no.bouvet.sandvika.oauth2: TRACE
