server:
  port: 9191
  servlet:
    context-path: /as
    session:
      timeout: 60 # Session timeout in seconds, to require periodic client re-authentication

security:
  oauth2:
    authorization:
      jwt:
        key-value: secret-jwt-key # Access token shared secret

bouvet:
  authorization:
    users:
      - username: oauth2-user
        password: user-password
        authorities:
          - USER
      - username: oauth2-admin
        password: admin-password
        authorities:
          - USER
          - ADMIN
    clients:
      - client-id: oauth2-client
        secret: client-password
        grant-types:
          - authorization_code
        scopes:
          - read
        redirect-uris:
          - http://localhost:9291/login

logging:
  level:
    org.springframework: DEBUG
    no.bouvet.sandvika.oauth2: TRACE
