server:
  port: 9292

security:
  oauth2:
    client:
      clientId: oauth2-client
      clientSecret: client-password
      accessTokenUri: http://localhost:9191/as/oauth/token
      userAuthorizationUri: http://localhost:9191/as/oauth/authorize
    resource:
      jwt:
        key-value: secret-jwt-key # Access token shared secret

logging:
  level:
    org.springframework: DEBUG
    no.bouvet.sandvika.oauth2: TRACE
